# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mediflow-be

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_076db202d5bf4a758477eb5613003ba6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_650bfcd06c2b4fb1af606cbb36c3549d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_076db202d5bf4a758477eb5613003ba6 }}/mediflow:${{ github.sha }}
        file: ./docker/prod.Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mediflow-be'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7d54e6cd27144490af642b14ec30d712 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_076db202d5bf4a758477eb5613003ba6 }}/mediflow:${{ github.sha }}'
